tap "cloud/tap", "git@jaxf-github.fanatics.corp:cloud/homebrew-tap.git"
tap "go-swagger/go-swagger"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "saulpw/vd"
brew "autoconf"
brew "automake"
brew "xz"
brew "awscli"
brew "consul", restart_service: true
brew "coreutils"
brew "direnv"
brew "elixir"
brew "fzf"
brew "git"
brew "git-lfs"
brew "gnutls"
brew "gnupg"
brew "go"
brew "golangci-lint"
brew "grpcurl"
brew "hadolint"
brew "openjdk"
brew "jmeter"
brew "jq"
brew "kafka"
brew "krb5"
brew "mas"
brew "mysql"
brew "nginx"
brew "node"
brew "node@14"
brew "podman"
brew "postgresql"
brew "postgresql@12"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ruby"
brew "rustup-init"
brew "tmux"
brew "ungit"
brew "vim"
brew "wget"
brew "yarn"
brew "zsh"
brew "cloud/tap/fanauth"
brew "cloud/tap/flywheel-client"
brew "cloud/tap/infractl"
brew "go-swagger/go-swagger/go-swagger"
brew "saulpw/vd/visidata"
cask "adoptopenjdk"
cask "commander-one"
cask "cyberduck"
cask "dbeaver-community"
cask "docker"
cask "firefox"
cask "github"
cask "insomnia"
cask "iterm2"
cask "java"
cask "meetingbar"
cask "react-proto"
cask "rectangle"
cask "sfdx"
cask "spotify"
cask "vagrant"
cask "visual-studio-code"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Install macOS Catalina", id: 0
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
